language: ruby
rvm:
  - 2.1.1
env:
  - CI_REPORTS=shippable/testresults COVERAGE_REPORTS=shippable/codecoverage
notifications:
  email:
    - charliec364@gmail.com
before_script:
  - mkdiir -p shippable/testresults
script:
  - rake test > shippable/testresults/results.out
