# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1cce21e012d17e1f74596e2370bf35fa0ce3aa81d1e08f88f0dc20a192154903ae48e4f9e0374d41fd8c7c3ee35761b7c09291a807f1916040a4382ab7978d94

test:
  secret_key_base: 19e413babd1b06e21690cea3745ffb1c04f4743037f6ed8259c5d6e10667a405ec0b6f7e405c211d7602e087c0b07c44a840565f29b09d42a4cf645420d32142

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
